# A Simple Julia Showcase Tutorial 
## Jordan Jalving

## Getting started with Jupyter notebooks

### Running a cell
To execute code within a cell, select that cell and either (1) hit `Shift` and `Enter` or (2) hit the run button (the right pointing arrow) above.

In [1]:
1 + 1
2 + 2

4

# The Basics

## Printing

Use `println()` to print output and create a new line

In [4]:
print("I print, but don't create a new line.")
println("I print and add a new line.")
println("I should be on the next line.")

I print, but don't create a new line.I print and add a new line.
I should be on the next line.


## Assigning Variables

All we need is a variable name, value, and an equal's sign<br>
Julia will figure out types for us.

In [8]:
my_answer = 42
typeof(my_answer)

Int64

In [9]:
my_pi = 3.14159
typeof(my_pi)

Float64

To type a smiley cat, use tab completion to select the emoji name and then tab again

In [ ]:
# \:smi + <tab> --> select with down arrow + <enter> ---> <tab> + <enter> to complete

In [11]:
😺 = "smiley cat!"
typeof(😺)

String

After assigning a value to a variable, we can reassign a value of a different type to that variable without any issue.

In [12]:
😺 = 1

1

In [13]:
typeof(😺)

Int64

LaTeX characters are also possible and easy to write <br>
\alpha + tab will create the greek symbol

In [20]:
α = r"\alpha"   #this is a raw string
δ = r"\delta"
Ξ = r"\Xi"
ϵ = r"\epsilon";

## Commenting

In [ ]:
# You can leave comments on a single line using the pound/hash key

In [ ]:
#=

For multi-line comments, 
use the '#= =#' sequence.

=#

## Basic Math

In [21]:
sum = 3 + 7

10

In [22]:
difference = 10 - 3

7

In [23]:
product = 20 * 5

100

In [24]:
quotient = 100 / 10

10.0

In [25]:
power = 10 ^ 2

100

# Data structures

The Default Structures
1. Tuples and NamedTuples
2. Dictionaries
3. Arrays

In [ ]:
tuple_animals = ("dog","cat","badger")
array_animals = ["dog","cat"]
set_animals = Set("dog","dog","badger")  # contains 2 elements
dict_animals = Dict("Cash" => "Dog","Bucky" => "Badger")

## Tuples

We can create a tuple by enclosing an ordered collection of elements in `( )`.

Syntax: <br>
```julia
(item1, item2, ...)```

In [27]:
myfavoriteanimals = ("parrots", "dogs", "possums")`

("parrots", "dogs", "possums")

In [28]:
myfavoriteanimals[1]

"parrots"

tuples are immutable

In [29]:
myfavoriteanimals[1] = "otters"

MethodError: MethodError: no method matching setindex!(::Tuple{String,String,String}, ::String, ::Int64)

## Dictionaries
Syntax:
```julia
Dict(key1 => value1, key2 => value2, ...)```

In [30]:
myphonebook = Dict("Jerry" => "867-5309", "George" => "555-2368")

Dict{String,String} with 2 entries:
  "Jerry"  => "867-5309"
  "George" => "555-2368"

In [31]:
myphonebook["Jerry"]

"867-5309"

In [36]:
myphonebook["Kramer"] = "555-FILK"

"555-FILK"

In [ ]:
myphonebook

We can delete Kramer from our contact list - and simultaneously grab his number - by using `pop!`

In [37]:
pop!(myphonebook, "Kramer")

"555-FILK"

In [ ]:
myphonebook

## Arrays
Syntax: <br>
```julia
[item1, item2, ...]```

### NOTE: Julia uses 1-based indexing

In [38]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

5-element Array{String,1}:
 "Ted"     
 "Robyn"   
 "Barney"  
 "Lily"    
 "Marshall"

The `1` in `Array{String,1}` means this is a one dimensional vector.  An `Array{String,2}` would be a 2d matrix, etc.  The `String` is the type of each element.

In [40]:
numbers = [1, 1, 2, 3, 5, 8, 13]

7-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13

In [ ]:
mixture = [1, 1, 2, 3, "Ted", "Robyn"]

In [ ]:
myfriends[3]

In [ ]:
myfriends[3] = "Baby Bop"

In [41]:
push!(numbers, 21)

8-element Array{Int64,1}:
  1
  1
  2
  3
  5
  8
 13
 21

In [42]:
pop!(numbers)

21

## Array Constructors

In [43]:
rand(4, 3)

4×3 Array{Float64,2}:
 0.759004  0.842979   0.87211  
 0.416812  0.120844   0.743867 
 0.91764   0.0419698  0.504693 
 0.216072  0.463645   0.0503647

In [44]:
rand(4, 3, 2)

4×3×2 Array{Float64,3}:
[:, :, 1] =
 0.946081  0.33725   0.366069
 0.278213  0.557588  0.238905
 0.500168  0.822011  0.664873
 0.445525  0.552254  0.827263

[:, :, 2] =
 0.761958  0.812939  0.969887
 0.603705  0.310735  0.560186
 0.529392  0.417026  0.25565 
 0.615711  0.276579  0.380008

In [45]:
zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [50]:
v1 = Vector{Float64}(undef,3)
v2 = Array{Float64,1}(undef,5)
println(v1)
println(v2)
v1 .= 2
println(v1)

[2.3342e-313, 1.9098e-313, 4.24399e-314]
[1.37445e-315, 1.37445e-315, 1.37445e-315, 1.37445e-315, 1.37445e-315]
[2.0, 2.0, 2.0]


## Copying Arrays

Arrays are assigned by reference

In [51]:
println(numbers)
newnumbers = numbers
newnumbers[1] = 404
println(numbers)

[1, 1, 2, 3, 5, 8, 13]
[404, 1, 2, 3, 5, 8, 13]


In [52]:
# First, restore fibonacci
numbers[1] = 1
println(numbers)
newnumbers = copy(numbers)
newnumbers[1] = 404
println(numbers)

[1, 1, 2, 3, 5, 8, 13]
[1, 1, 2, 3, 5, 8, 13]
